FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    wget build-essential \
    g++ \
    subversion git git-flow cmake \
    python-virtualenv python3-virtualenv \
    clang-tidy splint cppcheck \
    valgrind lcov

